### ISSUE TITLE
The "Change font size" button does not work.

### ISSUE THREAD

**Issue by maxime-bc** [ankitskvmdam/clean-jsdoc-theme#101]
**Describe the bug**

Hello, when I click on the "Change font size" button icon, nothing happens.

As soon as the page has finished loading, the following error appears in the console.

I have tried with both Firefox and Chrome.

- Firefox console :

```js
Uncaught TypeError: t is null
    processAllPre http://127.0.0.1:8081/scripts/core.min.js:1
    onDomContentLoaded http://127.0.0.1:8081/scripts/core.min.js:23
    EventListener.handleEvent* http://127.0.0.1:8081/scripts/core.min.js:23
core.min.js:1:4190
    processAllPre http://127.0.0.1:8081/scripts/core.min.js:1
    onDomContentLoaded http://127.0.0.1:8081/scripts/core.min.js:23
    (Async: EventListener.handleEvent)
    <anonymous> http://127.0.0.1:8081/scripts/core.min.js:23
```

- Chrome console :

```js
core.min.js:1 Uncaught TypeError: Cannot read properties of null (reading 'getBoundingClientRect')
    at processAllPre (core.min.js:1:4192)
    at onDomContentLoaded (core.min.js:23:1505)
processAllPre @ core.min.js:1
onDomContentLoaded @ core.min.js:23
DevTools failed to load source map: Could not load content for http://127.0.0.1:8081/scripts/third-party/popper.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:8081/scripts/third-party/tippy-bundle.umd.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

I don't know if these errors are related to the button not working.

**To Reproduce**

1 - Build the documentation : ``jsdoc --configure jsdoc.json --verbose``,
2 - Open the documentation with Firefox (for example): ``firefox docs/index.html``,
3 - When the page has finished loading, an error is present in the console and the "Change font size" button does nothing.

**Expected behavior**

A tooltip for changing the font size should appear.

**Desktop :**
 - OS: Rocky Linux 8.6
 - Browser : Firefox 101.0.1, Chrome 102.0.5005.115

**Additional context**

``jsdoc`` version : 3.6.10
``clean-jsdoc-theme`` version : 4.0.4

My ``jsdoc.json`` file :

```json
{
  "source": {
    "include": [
      "src"
    ],
    "includePattern": ".js$",
    "excludePattern": "(node_modules/|docs)"
  },
  "plugins": [
    "plugins/markdown"
  ],
  "templates": {
    "cleverLinks": true,
    "monospaceLinks": true
  },
  "opts": {
    "encoding": "utf8",
    "readme": "./README.md",
    "destination": "docs/",
    "recurse": true,
    "verbose": true,
    "template": "./node_modules/clean-jsdoc-theme",
    "theme_opts": {
      "base_ur": "http://localhost:8081",
      "default_theme": "light",
      "title": "My doc title"
    },
    "markdown": {
      "hardwrap": false,
      "idInHeadings": true
    }
  }
}
```

**Comment by ankitskvmdam** [comment]
Hi @maxime-bc Thanks for reporting this bug. Yes this bug is related to other issue but it led to the button. I will look into it.

**Comment by ankitskvmdam** [comment]
Hi @maxime-bc , I have released v4.0.5 in which this bug is fixed. Could you be able to check?

**Comment by ankitskvmdam** [comment]
Also in the `theme_opts` you have used `base_ur` instead of `base_url`.

**Comment by ankitskvmdam** [comment]
Closing this issue. @maxime-bc feel free to open it if it is not resolved for you.

**Comment by maxime-bc** [comment]
I've just tested the version 4.0.5 and it solves the issue. Thanks !
