### ISSUE TITLE
The default value of a constant array is rendered incorrectly.

### ISSUE THREAD

**Issue by maxime-bc** [ankitskvmdam/clean-jsdoc-theme#102]
**Describe the bug**

Hello, when documenting a constant with ``@constant``, if the ``@type`` of the constant is Array, the ``@default`` value will be rendered incorrectly.

**To Reproduce**

1 - ``jsdoc.json`` content :

```json
{
  "source": {
    "include": [
      "src"
    ],
    "includePattern": ".js$",
    "excludePattern": "(node_modules/|docs)"
  },
  "plugins": [
    "plugins/markdown"
  ],
  "opts": {
    "encoding": "utf8",
    "readme": "./README.md",
    "destination": "docs/",
    "recurse": true,
    "verbose": true,
    "template": "./node_modules/clean-jsdoc-theme",
    "theme_opts": {
      "default_theme": "light"
    },
    "markdown": {
      "hardwrap": false,
      "idInHeadings": true
    }
  }
}
```

2 - Write a jsdoc comment as bellow :
```js
    /**
     * This is a number array.
     * @constant
     * @type Array<number>
     * @default
     */
    NUMBER_ARRAY: [1, 2, 3],
```

3 - The generated documentation entry will look like this :

![image](https://user-images.githubusercontent.com/49453941/174013510-31bcfe9f-f1d9-44b4-ab9e-ccb16872df28.png)

The default array value isn't rendered correctly.

**Expected behavior**

When using the default jsdoc theme, the default array value is rendered correctly :

![image](https://user-images.githubusercontent.com/49453941/174014529-0d35fa67-147d-4b6b-bde6-7e5cb4407b55.png)

**Desktop :**
  - OS: Rocky Linux 8.6
  - Browsers : Firefox 101.0.1, Chrome 102.0.5005.115

**Additional context :**

``jsdoc`` version : 3.6.10
``clean-jsdoc-theme`` version : 4.0.5

**Comment by ankitskvmdam** [comment]
Hi @maxime-bc , Thanks for reporting this. I will look into it and try to release a patch by tomorrow.

**Comment by maxime-bc** [comment]
Ok, thanks !
