### ISSUE TITLE
A `null` key is cached instead of `font-size` on initial page load

### ISSUE THREAD

**Issue by rdipardo** [ankitskvmdam/clean-jsdoc-theme#109]
**Describe the bug**

On page load, `core.js` looks in local storage for a font size:

https://github.com/ankitskvmdam/clean-jsdoc-theme/blob/a69b404443b2d5d29ee30ae10583d7bc041a2f46/static/scripts/core.js#L408-L418

When storage is empty, a key of `null` is returned and then stored with the current font size value:

![init-page-null-key](https://user-images.githubusercontent.com/59004801/175831275-a01183a8-5069-4bee-81d2-d8578838ac69.png)

The `null` entry is never updated, because clicking the "Change font size" button creates a new, proper key:

![post-toggle-key](https://user-images.githubusercontent.com/59004801/175831295-8a1c18c0-6f2c-4e07-a83c-fa4ecd8b1130.png)

**To Reproduce**

1. Go to <https://ankdev.me/clean-jsdoc-theme/v4/>
2. Open the Developer Tools panel (<kbd>F12</kbd> or <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd> 
3. Select the Application tab and inspect Local Storage for the `https://ankdev.me` domain
4. A `null` key has the value 16

**Expected behavior**

A `font-size` key has the value 16

**Screenshots**

_See description above_

**Desktop (please complete the following information):**
 - OS: `Linux 4.19.0-20-amd64 #1 SMP Debian 4.19.235-1 (2022-03-17) x86_64 GNU/Linux`
 - Browser: Opera
 - Version: 88.0.4412.40

**Additional context**

This change will ensure the font size key is always a valid string:

~~~diff
--- a/static/scripts/core.js
+++ b/static/scripts/core.js
@@ -413,7 +413,7 @@ function updateFontSize(fontSize) {
     }
     updateFontSize(n);
   } else {
-    localStorage.setItem(fontSizeInLocalStorage, fontSize);
+    localStorage.setItem(fontSizeLocalStorageKey, fontSize);
   }
 })();
 
~~~

**Comment by ankitskvmdam** [comment]
Thanks, @rdipardo, it is beautiful that you have spotted this issue.
