### ISSUE TITLE
Solve source map load errors.

### ISSUE THREAD

**Issue by github-nilsson** [ankitskvmdam/clean-jsdoc-theme#111]
Looking at the documentation with DevTools open give you two source map load errors, one for scripts/third-party/popper.min.js.map and one for scripts/third-party/tippy-bundle.umd.min.js.map. Either include the map files in that directory or remove the references to them a the end of popper.js and tippy.js.

**Comment by ankitskvmdam** [comment]
Thanks! I will remove the source map reference.
