### ISSUE TITLE
Make the output relocatable

### ISSUE THREAD

**Issue by github-nilsson** [ankitskvmdam/clean-jsdoc-theme#112]
The current output can't be moved into any subdirectory of a webserver due to the use of this.baseURL. Everything javascript-based, like search, is easily solved using document.location instead.

```diff
     <script>
       // Global variables
-      var baseURL = "<?js= this.baseURL ?>"
+      var baseURL = document.location.pathname;
+      baseURL = baseURL.substr(0,baseURL.lastIndexOf("/")+1);
     </script>
```
The use of this.baseURL in sidebar-title.tmpl must also be changed.

**Comment by ankitskvmdam** [comment]
Hi @github-nilsson, the purpose of `this.baseURL` is to set the base URL for the output. So, let's say the domain name is `https://example.com` and we are placing our doc/output to `/docs/v1`, the the value of the `this.baseURL` should be `https://example.com/docs/v1/`.

**Comment by github-nilsson** [comment]
Yes, but that isn't a good solution as you can't move it to a different directory, and you have to build multiple times if you wan to publish the documentation in multiple places.

**Comment by ankitskvmdam** [comment]
Yes, that is true. What do you think about this: I will set the default value of `this.baseURL` as what you have suggested, and later if we find that there is no need for `this.baseURL` then we will remove it.

Thanks for this insight.

**Comment by ankitskvmdam** [comment]
Fix: https://github.com/ankitskvmdam/clean-jsdoc-theme/commit/6bb193a1abbbd2b16a70e8ed4b17a117a12b5f34
