### ISSUE TITLE
Unordered lists rendered with bullet points

### ISSUE THREAD

**Issue by NKHnC** [ankitskvmdam/clean-jsdoc-theme#125]
**Is your feature request related to a problem? Please describe.**

I am trying to create a welcome page using markdown parser, however when using an unordered list the bullet points are not rendered in the theme. 

**Describe the solution you'd like**

The theme renders the unordered list with correct bullet points, such as those in a typical markdown renderer. Note: Different bullet points for further indented lists. 

**Describe alternatives you've considered**

An alternative would be custom CSS in the json config or markdown file.

**Additional context**

Example:

```
- Test 1 
- Test 2
  - Test 2.1
    - Test 2.2
- Test 3
  - Test 3.2
```

- Test 1 
- Test 2
  - Test 2.1
    - Test 2.2
- Test 3
  - Test 3.2

**Comment by ankitskvmdam** [comment]
Hi @NKHnC , Thank you for this issue.

There are a couple of things you can do.
The first approach is to use the `create_style` property (https://github.com/ankitskvmdam/clean-jsdoc-theme#add-styles): 
```json
"create_style": ".main-wrapper ul { list-style: revert }"
```

More on `revert`: https://developer.mozilla.org/en-US/docs/Web/CSS/revert

You can also create a new CSS file and include all the custom CSS you want to add like this:
```css
/* static/main.css */

.main-wrapper ul {
    list-style: revert
}

.other-styles {
    background: red
}
```
Let's say you have created the above CSS file in the static folder and named it main.css. To include this file CSS file, you can use the `include_css` property (https://github.com/ankitskvmdam/clean-jsdoc-theme#add-custom-css-files):

```json
"include_css": ["./static/main.css"]
```
The file's location should be relative to the path of jsdoc configs file.

> Note: Both `include_css` and `create_style` properties should be the child of `theme_opts`.

**Comment by ankitskvmdam** [comment]
Hi @NKHnC, did you able to solve the issue you were facing?

**Comment by NKHnC** [comment]
Good day @ankitskvmdam, 
Firstly thank you very much for the above explanation, I'm still abit new to the whole CSS/HTML world. 
Yes, you did solve the issue and I appreciate you the quick response.

**Comment by ankitskvmdam** [comment]
I am glad that your issue is solved. Feel free to raise any issue you have. We all are learners here.
