### ISSUE TITLE
Extra line breaks in code blocks

### ISSUE THREAD

**Issue by Viiprogrammer** [ankitskvmdam/clean-jsdoc-theme#128]
**Describe the bug**

**To Reproduce**

1. Go to [example](https://ankdev.me/clean-jsdoc-theme/v4/)
2. Click on Copy button or select code and press copy (or `Ctrl+C`)
3. Paste code in favorite IDE or other text editor or text field
4. Code has extra line breaks:

```
"opts": {

  "template": "node_modules/clean-jsdoc-theme"

}
```
Or when I copy with context menu (only with context menu) and paste code in text field with github issue description, it HTML:

```
<pre class="prettyprint source lang-json" data-lang="code" style="max-height: 472px;" id="ScDloZOMdL2"><code class="hljs language-json">

"opts": {
--


</code></pre><pre class="prettyprint source lang-json" data-lang="code" style="max-height: 472px;" id="ScDloZOMdL2"><code class="hljs language-json"><span class="hljs-punctuation">}</span></code></pre>
```

and in Chrome 95.0.4638.69 same problem, but if I copy with context menu and paste to GitHub issue description:

```
  | "opts": {
-- | --
  | "template": "node_modules/clean-jsdoc-theme"
  | }
```

and with copy button

```
	"opts": {

	  "template": "node_modules/clean-jsdoc-theme"

	}
```

**Expected behavior**
Exactly the same code as in the example

```
"opts": {
  "template": "node_modules/clean-jsdoc-theme"
}
```

**Desktop:**
 - **OS:** GNU/Linux, Ubuntu
 - **Browser:** Firefox
 - **Version:** 103.0 (64 bit)

https://youtu.be/oR7uxy0Pwos

**Comment by ankitskvmdam** [comment]
Hi @Viiprogrammer thanks for the issue and the demo. I will create a patch release for this as soon as possible.

Thanks again for taking time to report this issue.

**Comment by ankitskvmdam** [comment]
Fixed in https://github.com/ankitskvmdam/clean-jsdoc-theme/commit/6cccb00d316a342de19f97717f21efcce2682229
