### ISSUE TITLE
Design bug, no space after code block

### ISSUE THREAD

**Issue by Viiprogrammer** [ankitskvmdam/clean-jsdoc-theme#134]
**Describe the bug**

![image](https://user-images.githubusercontent.com/17622604/182675952-0e12ac33-eda3-48f4-82e6-5a7ebbe2316b.png)

```
  /**
   * Text
   * > Text
   * > ```js
   * > code
   * > ```
   *
   * > Note that commands are not matched in captions or in the middle of the text.
   */
```

**Desktop:**
 - OS: GNU/Linux, Ubuntu
 - Browser: Firefox
 - Version: 103.0 (64 bit)

**Comment by ankitskvmdam** [comment]
Thanks for reporting this. I will work on this over the weekend.

**Comment by ankitskvmdam** [comment]
Also, it will work perfectly fine if you do:
```
/**
   * Text
   * > Text
   * 
   * ```js
   *   code
   *```
   *
   * > Note that commands are not matched in captions or in the middle of the text.
   */
```

Remove `>` from code block.
