### ISSUE TITLE
History back/forward buttons doesn't work (History API)

### ISSUE THREAD

**Issue by Viiprogrammer** [ankitskvmdam/clean-jsdoc-theme#135]
**Describe the bug**

No reaction to back / forward history buttons

**Expected behavior**

Back / forward history buttons work correctly

**Video**

https://user-images.githubusercontent.com/17622604/183160874-30d95559-753f-4feb-996a-e0a0d5c3dc79.mp4

**Desktop:**
 - **OS:** GNU/Linux, Ubuntu
 - **Browser:** Firefox
 - **Version:** 103.0 (64 bit)

**Comment by Viiprogrammer** [comment]
Hmm, maybe this is not a bug :roll_eyes:, but it might be worth making it to work :expressionless:

**Comment by ankitskvmdam** [comment]
Thanks for reporting, and yes it will be nice if it works.

I will work on this as well.
