### ISSUE TITLE
Table of content links are never active if they point to content located at the bottom of a page.

### ISSUE THREAD

**Issue by maxime-bc** [ankitskvmdam/clean-jsdoc-theme#140]
Hello,

Inside the table of content, if we click on a link that points to content located at the bottom of a page, the link will not change its status and never be active.

**To Reproduce**

For example, when visiting the [`clean-jsdoc-theme` home page](https://ankdev.me/clean-jsdoc-theme/v4/), if we click on **Developing** in the table of content, the **Developing** link will be active. But any following link (**Contributing**, **Thanks**, **Contact**, **License**) will never be active if click on them as they point to content located at the bottom of the page.

**Expected behavior**

Clicking any link inside the table of content should trigger their active status.

**Desktop :**
 - OS: Ubuntu 22.04.1 LTS 
 - Browser: Firefox 104.0

**Comment by ankitskvmdam** [comment]
Yes, this is a known bug. I have no idea how to make it active when we are on the last page. I guess this is the limitation in the [Tocbot](https://tscanlin.github.io/tocbot/) library (We are using tocbot under the hood for TOC).

I will try to find some time to solve this issue. In the meantime, if you have any suggestions/solutions then please feel free to share.
