### ISSUE TITLE
Home page title customisation.

### ISSUE THREAD

**Issue by maxime-bc** [ankitskvmdam/clean-jsdoc-theme#141]
Hello,

The home page title is currently [hard-coded](https://github.com/ankitskvmdam/clean-jsdoc-theme/blob/master/publish.js#L1003), we can see it when visiting [`clean-jsdoc-theme`](https://ankdev.me/clean-jsdoc-theme/v4/).

It could be great if we could customize the page title (for example giving it the same value as the sidebar title). This could be done by adding a new option to the JSDoc config.

**Comment by ankitskvmdam** [comment]
Thanks for this feature request. I will try to implement this.
