### ISSUE TITLE
Summary tag doesn't add class to the correct html element

### ISSUE THREAD

**Issue by VanWeapon** [ankitskvmdam/clean-jsdoc-theme#142]
**Describe the bug**

When adding a jsdoc `@summary` tag, the generated html looks like so:

```html
<p class="summary"></p>
<p>Actual summary content text</p>
<p></p>
... rest of document
```
The summary class is attached to an empty paragraph tag and the docs content is added to an unstyled p tag. 

**To Reproduce**

1. Add an `@summary` tag to any class method documentation
2. observe the output html when inspected

**Expected behavior**

The html class "summary" should be on a div which wraps the `<p>` tag containing the summary text. This is so that we can  target the summary class element accurately for adding styles to it with css or js

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: all
 - Version latest

**Comment by ankitskvmdam** [comment]
Thanks for reporting this. I will look into it.
