### ISSUE TITLE
All lines of code after the first line has tabulation character at the start

### ISSUE THREAD

**Issue by Viiprogrammer** [ankitskvmdam/clean-jsdoc-theme#144]
**Describe the bug**

When I copy code with context menu / copy button / etc. it has tabulation character before all lines excludes first

**To Reproduce**

1. Go to https://ankdev.me/clean-jsdoc-theme/v4/#example-jsdoc-config
2. Click on copy button / CTRL+C / context menu copy
3. Paste code in whatever editor or field

**Expected behavior**
No tabulation on start of lines

**Screenshots**

![image](https://user-images.githubusercontent.com/17622604/187079707-3495273e-0d7e-46e9-967a-6b5a23b2f3df.png)

**Desktop:**
 - **OS:** GNU/Linux, Ubuntu
 - **Browser:** Firefox
 - **Version:** 103.0 (64 bit)

and 

**Desktop:**
 - **OS:** GNU/Linux, Ubuntu
 - **Browser:** Google Chrome
 - **Version:** 95.0.4638.69 (64 bit)

**Additional context**

I think it not fully fixed #128

**Comment by ankitskvmdam** [comment]
Yes, you are correct. I will look into it. Thanks for reporting it.
