### ISSUE TITLE
Add support for jsdoc@4.0.0

### ISSUE THREAD

**Issue by maxime-bc** [ankitskvmdam/clean-jsdoc-theme#173]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

This November, `jsdoc` released a [version 4.0.0](https://github.com/jsdoc/jsdoc/blob/main/CHANGES.md#400-november-2022) and it would be great that `clean-jsdoc-theme` support it.

In this new version, the `taffyDB` module has been replaced by `salty`.

The steps to update an existing template with `salty` are explained [here](https://github.com/jsdoc/jsdoc/tree/main/packages/jsdoc-salty#use-salty-in-a-jsdoc-template).

**Comment by ankitskvmdam** [comment]
`clean-jsdoc-theme v4.1.12` now supports jsdoc 4.
