### ISSUE TITLE
Question: @readonly

### ISSUE THREAD

**Issue by SxmplyJythyy** [ankitskvmdam/clean-jsdoc-theme#176]
Is @ readonly supported in this theme? @ deprecated works but not @ readonly

**Comment by ankitskvmdam** [comment]
Could you explain the issue more? There is no intention to remove the support for @readonly.

**Comment by ankitskvmdam** [comment]
Also, could you please try version 4.2.2, in version 4.2.1 type-signature was not properly configured. I have fixed that issue in v4.2.2. It is released today, maybe it has the fix you are looking for.

**Comment by SxmplyJythyy** [comment]
> Could you explain the issue more? There is no intention to remove the support for @readonly.

Mhm, when using @ deprecated it shows as normal in the documentation, but whenever I use @ readonly it doesn't display any notice that is it read only, yet deprecated displays. I am using the latest version.

**Comment by ankitskvmdam** [comment]
Got it!
Please switch to `v4.2.2`. It will now show the indication for the readonly variables. If you will not able to see please share a reproducible repository.

I tried it today and it was working.
![image](https://user-images.githubusercontent.com/22586210/209968685-f2343ad9-eac8-4c55-90ca-65b9c1406e4f.png)

**Comment by SxmplyJythyy** [comment]
> Got it! Please switch to `v4.2.2`. It will now show the indication for the readonly variables. If you will not able to see please share a reproducible repository.
> 
> I tried it today and it was working. ![image](https://user-images.githubusercontent.com/22586210/209968685-f2343ad9-eac8-4c55-90ca-65b9c1406e4f.png)

Got it, thanks for letting me know. It works now and as It seems as well the file reference link/name is also fixed. Thank you.
![image](https://user-images.githubusercontent.com/77365955/209980474-663e43bb-a4a3-4c8b-8486-43e2ccb6e8b1.png)
![image](https://user-images.githubusercontent.com/77365955/209980491-be6bdb96-9a50-442d-acb3-a882f1e26e55.png)
