### ISSUE TITLE
css problem  when the desc of function parameter  is big 

### ISSUE THREAD

**Issue by carlosjpr-collab** [ankitskvmdam/clean-jsdoc-theme#177]
i got a bug in the css when the desc of function parameter  is big 

![image](https://user-images.githubusercontent.com/38086105/209964693-a732c21f-3315-4d7f-a1f9-5e7715f8dcfc.png)

**Comment by ankitskvmdam** [comment]
Could you please share a repo reproducing this bug?

**Comment by ankitskvmdam** [comment]
Fixed in v4.2.2 (c1ea0a0bc20e8f5a644e428c1c8278fd7009a7a0)

@carlosjpr-collab If you still face the issue feel free to reopen this issue.
