### ISSUE TITLE
Bug - Source File Title: Text Size

### ISSUE THREAD

**Issue by SxmplyJythyy** [ankitskvmdam/clean-jsdoc-theme#178]
**Describe the bug**

Title text too big to see fully

**To Reproduce**

1) Steps to reproduce the behavior:
2) Generate your docs with the theme
3) Open it, and open a class
4) Click the source link to the file
Result: Title is too big

**Expected behavior**

title text fixed to screen size

**Screenshots**

![image](https://user-images.githubusercontent.com/77365955/209996205-e6bc9057-fc2f-4af6-a1e4-6827fe65c72a.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Google Chrome
 - Browser Version: 108.0.5359.125 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
N/A - Not Tested

**Additional**
I am using latest, v4.2.2

**Comment by SxmplyJythyy** [comment]
Source Repo: https://github.com/SxmplyJythyy/sxmplyjythyy-api

**Comment by ankitskvmdam** [comment]
This is because the name/title is very big. To fix this, you can create a [css rule](https://github.com/ankitskvmdam/clean-jsdoc-theme#add-styles):

```json5
"theme_opts": {
  "create_style": ".source-page #title { word-break: break-all }"
}
```

You can also include a your custom css, [Learn More](https://github.com/ankitskvmdam/clean-jsdoc-theme#add-custom-css-files)
