### ISSUE TITLE
Search result is displayed broken

### ISSUE THREAD

**Issue by Viiprogrammer** [ankitskvmdam/clean-jsdoc-theme#184]
**Describe the bug**

Search result is displayed broken

**To Reproduce**
```js
/**
  * This object represents one size of a photo or a [file](https://core.telegram.org/bots/api/#document)
  *
  * / [sticker](https://core.telegram.org/bots/api/#sticker)
  * thumbnail.
  *
  * @typedef {object} PhotoSize
  * @property {string} file_id Identifier for this file, which can be used to download or reuse the file
  * @property {string} file_unique_id Unique identifier for this file, which is supposed to be the same over time and
  *   for different bots. Can't be used to download or reuse the file.
  * @property {number} width Photo width
  * @property {number} height Photo height
  * @property {number} [file_size] *Optional*. File size in bytes
  * @see https://core.telegram.org/bots/api/#photosize
*/
```

**Screenshots**
![изображение](https://user-images.githubusercontent.com/17622604/210271468-eb5ddf34-5567-4b9e-810f-be5362cc0ead.png)
![изображение](https://user-images.githubusercontent.com/17622604/210271498-222a541d-6972-47d5-9165-1a75aaa6a518.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version 108.0 (64bit)

**Additional context**

Repo: https://reference.opengram.dev/

**Comment by ankitskvmdam** [comment]
I will look into this.

**Comment by ankitskvmdam** [comment]
Fixed in https://github.com/ankitskvmdam/clean-jsdoc-theme/commit/b43ddea840f4fcc27a880043514df9433b4cb95a

**Comment by ankitskvmdam** [comment]
@Viiprogrammer `v4.2.3` is release. In `v4.2.3` the search is fixed.
