### ISSUE TITLE
StaticFiles are not copied

### ISSUE THREAD

**Issue by ivmartel** [ankitskvmdam/clean-jsdoc-theme#185]
**Describe the bug**

The files of the jsdoc property `templates.default.staticFiles.include` are not copied to the output directory. This was working with v4.2.0 but stopped working with v4.2.1.

**To Reproduce**

1. Define the jsdoc prop `templates.default.staticFiles.include`
2. Add an image to a markdown tutorial file with `![my-image](my-image.png)`
3. Generate documentation
4. The image file is not copied in the output dir
5. Go to the generated tutorial page, the image is not shown

**Expected behavior**

The files should be copied to the output directory so that pages find them.

**Additional context**

Works with v4.2.0, stopped with v4.2.1

**Comment by ivmartel** [comment]
Maybe related to changes in the `clean-jsdoc-theme-helper.js file, see [diff](https://github.com/ankitskvmdam/clean-jsdoc-theme/commit/a04870b969d9d6fb8361bb7e53bdcb10f98189fc#diff-72604984ccbe5fd201fe49e2f2217825efdbcd5e3e8459deea56b0d6bb23c503).

**Comment by ankitskvmdam** [comment]
Thanks for reporting. I will look into it today..

**Comment by ankitskvmdam** [comment]
@ivmartel Did you use `v4.2.2`?

**Comment by ivmartel** [comment]
Yes, same as v4.2.1, no files copied...

**Comment by ankitskvmdam** [comment]
Could you please share your config file/repo? It would be very helpful to debug.

**Comment by ankitskvmdam** [comment]
I tried it in my local and it is working.

Also, the recommend way to copy/add static files in `clean-jsdoc-theme` is using [static_dir](https://github.com/ankitskvmdam/clean-jsdoc-theme/#add-static-dir), please consider using `static_dir`

**Comment by ivmartel** [comment]
repo: https://github.com/ivmartel/dwv
config: https://github.com/ivmartel/dwv/blob/develop/resources/doc/jsdoc.conf.json

I'm using the `staticFiles` as described in the jsdoc doc: [copying-static-files-to-the-output-directory](https://jsdoc.app/about-configuring-default-template.html#copying-static-files-to-the-output-directory)

**Comment by ankitskvmdam** [comment]
Got it!
The behaviour of copying static files in `jsdoc` is a bit different than `clean-jsdoc-theme`.

And yes you are right there is a bug in the publish code. I have fixed it here: https://github.com/ankitskvmdam/clean-jsdoc-theme/commit/62b4d8f209de29c489b228f1f08384fdaa0a111c

Please update to `v4.2.3`

**Comment by ivmartel** [comment]
Looking good, files are copied with v4.2.3, thanks!
