### ISSUE TITLE
Search only searches Globals, nothing else

### ISSUE THREAD

**Issue by Nikki1993** [ankitskvmdam/clean-jsdoc-theme#186]
Greetings,

I am a bit confused on how the search function works, it was my understanding that it searches the entire jsdoc not just global values but in my case I have methods under namespaces you can search for a namespace name but you can't search for individual methods within that namespace. It returns nothing. Is there any way to enable search of individual methods?

For instance I have a namespaced method called `focusOnAsset` that you can see below the search and yet search results show nothing. 

<img width="966" alt="Screenshot 2023-01-25 at 14 39 42" src="https://user-images.githubusercontent.com/1446529/214565711-a22fb38c-f7f7-4b63-8990-2e96cafbb71d.png">

**Comment by ankitskvmdam** [comment]
It should search the methods as well.

If possible, could you please share the repo? This will help in debugging.

**Comment by ankitskvmdam** [comment]
This is fixed and I will publish it soon. Thank you!

**Comment by Nikki1993** [comment]
Hey,

Thank you kindly for switch implementation. Great stuff! One minor thing is that when searching for items and then pressing Enter it doesn't scroll to view, so when the item is in a big list the search result brings you to correct namespace but doesn't scroll to the searched item.

**Comment by ankitskvmdam** [comment]
Is it only happening for namespace?

For me it scrolls to the searched item. What browser are you using? and OS? Also, is it possible to share a minimum repo that reproduces the same issue. That will be very helpful.

**Comment by Nikki1993** [comment]
I will create a minimum repo during the week, can't share the code of this repo as its private but here is the video of me searching and its not scrolling all the way down to where it should be.

Chrome 109, MacOS 13.2 

https://user-images.githubusercontent.com/1446529/216994677-9ae38f4b-fda7-43b5-a0e5-929248b3692e.mov

**Comment by ankitskvmdam** [comment]
Sure that will be helpful.

Also, did you enable the idInHeading options? Please look the below config file for reference. 

```json5
{
    "source": {
        "include": ["lib", "package.json", "README.md"],
        "includePattern": ".js$",
        "excludePattern": "(node_modules/|docs)"
    },
    "plugins": ["plugins/markdown"],
    "opts": {
        "encoding": "utf8",
        "readme": "./README.md",
        "destination": "docs/",
        "recurse": true,
        "verbose": true,
        "template": "./node_modules/clean-jsdoc-theme",
        "theme_opts": {
            "default_theme": "dark"
        }
    },
    "markdown": {
        "hardwrap": false,
        "idInHeadings": true
        // This is important for clean-jsdoc-theme, otherwise some features might not work.
    }
}
```


Under `markdown` you can see the `idInHeading` is enabled. This is important for scrolling.

If you have not enabled it then could you please test it after enabling?

**Comment by Nikki1993** [comment]
Yea I do have the option on still not doing. I will work on that reproducible repo.

**Comment by Nikki1993** [comment]
@ankitskvmdam i've created the repo https://github.com/Nikki1993/clean-jsdoc-theme-search-issue 

The issue is when you add `@alias` to functions, it breaks the anchor tags and thus reloads the page instead of navigating to the item. I've added an alias `test` to search for, click on that. The function is at the bottom of the page but instead of going to it the page reloads instead.

**Comment by ankitskvmdam** [comment]
Thanks! I will look into it as soon as possible.

**Comment by ankitskvmdam** [comment]
I looked into the repo that you shared. I think it is not the problem with the theme. It is how JSDoc build links.
Based on the repo you shared the search will work when you do the following changes:

```js
function create_public_interface(obj) {
    /**
     * @namespace obj.map
     */
    const map = obj.map;
   
   // ... other properties
    
    /**
     * @memberOf obj.map
     * @function
     * @alias obj.map.test    <--- THIS IS CHANGED PREVIOUSLY IT WAS `test` NOW `obj.map.test`
     */
    map.start9 = function () {}
   // ...other properties 
}
```

**Comment by ankitskvmdam** [comment]
@Nikki1993 Does it work?

**Comment by Nikki1993** [comment]
My apologies, busy work schedule last week. I am gonna try it later today.

**Comment by Nikki1993** [comment]
@ankitskvmdam confirming that it does indeed work. Would be cool to not have full path in the alias but that's jsdoc problem not yours. Thank you for all the help!
