### ISSUE TITLE
Ability to set source text to file name instead of full path.

### ISSUE THREAD

**Issue by jacobhumston-school** [ankitskvmdam/clean-jsdoc-theme#192]
**Is your feature request related to a problem? Please describe.**

Unless this is already possible (if so please lmk) I haven't figured out a way to prevent the source text from using the full path.

When I use the jsdoc default theme, it just displays the file name, which is the way I prefer it. The full path on my local machine isn't really relevant when it's displayed using GitHub pages.

**Describe the solution you'd like**

An option to change this behavior to the one I specified above would be preferred.

**Describe alternatives you've considered**

The best solution I've come up with is just not providing the source files all together, however that doesn't feel very end-user friendly.

```json
{
    "markdown": {
        "hardwrap": false,
        "idInHeadings": true
    },
    "templates": {
        "default": {
            "outputSourceFiles": false,
            "staticFiles": {
                "paths": ["tutorials/assets/"]
            }
        }
    },
    "opts": {
        "template": "node_modules/clean-jsdoc-theme"
    }
}
```

**Additional context**

![image](https://user-images.githubusercontent.com/113031145/216373706-1b64369e-b142-48ba-80ff-ff4b9ff87ad3.png)

**Comment by ankitskvmdam** [comment]
Thanks for reporting this. Yes it should only display the file name not the Full path.

I will look into it today.

**Comment by ankitskvmdam** [comment]
Which version of `clean-jsdoc-theme`you are using? Also is it possible to share the repo?

**Comment by jacobhumston** [comment]
Repo is https://github.com/Lovely-Experiences/sxcu.api and I'm currently using version 4.2.3

**Comment by ankitskvmdam** [comment]
I cloned the Repo and run the run `npm run generate-doc`. For me it is giving the correct output.

![image](https://user-images.githubusercontent.com/22586210/216789846-2fdec0ed-04bd-4616-9289-90bbb85a3ecb.png)

Could you please tell me your OS? I tested on Windows.

**Comment by jacobhumston** [comment]
> Could you please tell me your OS? I tested on Windows and WSL (Windows Subsystem for Linux).

The latest push to that repo (where the docs were generated) was on openSUSE, version is 15.3 if I'm not mistaken (https://get.opensuse.org/leap/15.3/). I've also generated on windows version 11 and had the same issue. I've been using the latest node.js LTS version.

**Comment by jacobhumston** [comment]
I tried again on windows version 11 and it continues to do the full path.
https://gyazo.com/cdeeab04e5bb827589fa1bd7a2679163

**Comment by ankitskvmdam** [comment]
I also tested it on node.js LTS version (18.14.0). It is working fine for me. 

I am not sure why it is happening but I guess it could be due to this: https://github.com/ankitskvmdam/clean-jsdoc-theme/blob/master/publish.js#L278-L286 and https://github.com/ankitskvmdam/clean-jsdoc-theme/blob/master/publish.js#L710-L719

The problem with me is that I am not able to reproduce. I will look more, but if you find any solution feel free to create a PR or share.
