### ISSUE TITLE
Disable source code inclusion

### ISSUE THREAD

**Issue by mrfigg** [ankitskvmdam/clean-jsdoc-theme#204]
**Is your feature request related to a problem? Please describe.**

Personally I dislike including the source code of my projects in the generated documentation as it generally feels like extra clutter.

**Describe the solution you'd like**

It would be great if there was a `includeSources` boolean option in `theme_opts` that would control whether or not to include source files in the generated documentation.

**Describe alternatives you've considered**

Manually going through and editing the generated files after creation, but that kind of defeats the purpose of JSdoc and is harder to work into automated workflows.

**Comment by ankitskvmdam** [comment]
@mrfigg Did you try jsdoc configuration to turn of source code generation?

Visit: https://github.com/ankitskvmdam/clean-jsdoc-theme/issues/60#issuecomment-807074900

You can do the following in your `jsdoc config file`:

```JSON5
{
    // ... other configs
    "templates": {
       // ... other template configs
       default: {
          outputSourceFiles: false       // <- This is important
       }
    },

   // Jsdoc theme config
   theme_opts: {}
}
```

More information on disabling source file: https://jsdoc.app/about-configuring-default-template.html#generating-pretty-printed-source-files

**Comment by mrfigg** [comment]
I was not aware options were inherited from the default template. Thanks, this works perfectly!

**Comment by ankitskvmdam** [comment]
No worries! Happy that it works.
