### ISSUE TITLE
Is there a way to disable alphabetization/sort in the navbar/sidebar?

### ISSUE THREAD

**Issue by mrfigg** [ankitskvmdam/clean-jsdoc-theme#205]
As the title asks, is there a way to disable alphabetization/sort in the navbar/sidebar? I would like each member/method/event to appear in the same order as they appear in my code, while still grouped by section.

**Comment by ankitskvmdam** [comment]
@mrfigg 
So, this option is not available right now. But thanks for creating the issue, I will try to work on this over the weekends. 

Expect this feature in the next release (Probably withing a week).

**Comment by mrfigg** [comment]
Thanks for the fast turn around!
