### ISSUE TITLE
ReDoS found in htmlminifier.js

### ISSUE THREAD

**Issue by uWottM8** [ankitskvmdam/clean-jsdoc-theme#222]
**Describe the bug**

ReDoS was found in htmlminifier.js (https://www.npmjs.com/package/html-minifier), which is installed as dependency.

**Additional context**

More information about issue: https://github.com/kangax/html-minifier/issues/1135

**Suggestions**

As suggested in thread above, you can use html-terser-minifier (https://www.npmjs.com/package/html-minifier-terser), which is actively maintained and fully compatible with minify-options of htmlminifier, but has no vulnerabilities.

Can you please update repo to use html-terser-minifier? :)

**Comment by ankitskvmdam** [comment]
@uWottM8 Thanks for creating this issue.

I will resolve this issue as soon as possible.

**Comment by DanielRuf** [comment]
I suggest reading my comments and especially https://github.com/kangax/html-minifier/issues/1135#issuecomment-2453437884 - because switching to `html-minifier-terser` will not fix this.

**Comment by ankitskvmdam** [comment]
Hi @DanielRuf,

Thanks for your reply. Could you guide us on how to resolve this issue?

**Comment by DanielRuf** [comment]
@ankitskvmdam as you can see at https://github.com/kangax/html-minifier/issues/1135#issuecomment-2453405484, there are a few possible solutions.

The best but probably most complex would be to patch the code with the regular expression (using `patch-package` or some other solution).

The less complex solution is to change the default options and clear `ignoreCustomFragments`, which would avoid the problematic code and add a warning in the documentation until it is fully patched in some way.

Other solutions would be:
* prevent that the code can run longer than some specified timeout
* sanitize / check / limit the input, that users can provide
* ... (any solution that reduces the risk of DoS by limiting the resources)
