### ISSUE TITLE
[Question] - How to Create Nav Link Dropdowns

### ISSUE THREAD

**Issue by adithyaakrishna** [ankitskvmdam/clean-jsdoc-theme#232]
I would really love to know how we can implement a dropdown in the nav links, something similar to the one in the below pictures :)

<img width="479" alt="Screenshot 2023-08-16 at 1 29 58 AM" src="https://github.com/ankitskvmdam/clean-jsdoc-theme/assets/23498248/9bdd869c-c8b4-467d-8a6b-c6dca239658b">

PS. @ankitskvmdam This theme is gorgeous 💯

**Comment by ankitskvmdam** [comment]
Thanks for using this theme.

To add a dropdown menu you have to use some javascript. Currently dropdown menu is not supported.

To include custom js you can use `include_js` options (https://github.com/ankitskvmdam/clean-jsdoc-theme#add-custom-script-files)

I will try to create a demo script over the weekend.

**Comment by adithyaakrishna** [comment]
Hey @ankitskvmdam 
Sure sounds great. We went ahead with having a new page instead of dropdown :)

There was also another problem/issue we faced, which was using unordered list using `-` or `*` through markdown. The bullet points weren't getting rendered

![Screenshot 2023-08-23 at 8 55 50 PM](https://github.com/ankitskvmdam/clean-jsdoc-theme/assets/23498248/46a02b41-070a-4945-a350-771efe617449)

**Comment by ankitskvmdam** [comment]
By default `clean-jsdoc-theme` doesn't render bullets. If you want to render then you need to create custom css/style.

There are two ways.

1. The easy one: https://github.com/ankitskvmdam/clean-jsdoc-theme#add-styles. You can do something as follows:
```json5
"theme_opts": {
  // ...other options
  "create_style": "article ul li { list-style: disc}",
}
```

2. The hard one: https://github.com/ankitskvmdam/clean-jsdoc-theme#add-custom-css-files. You can add custom css files. In those files you  can add the above css rules.

**Comment by adithyaakrishna** [comment]
Thank you so much, @ankitskvmdam. I really appreciate the quick response on it :)

PS. The new site of, https://3dmol.org/doc/index.html will have this theme, and I have become a huge fan of it 💯
