### ISSUE TITLE
Add option for automatic dark/light mode

### ISSUE THREAD

**Issue by EwanRoycroft** [ankitskvmdam/clean-jsdoc-theme#233]
**Describe the solution you'd like**

As many sites do, this theme could automatically detect the user's preference for light or dark mode [from their browser settings](https://web.dev/prefers-color-scheme/#supporting-dark-mode).

**Comment by ankitskvmdam** [comment]
Sure, I will try to add this feature today!

**Comment by EwanRoycroft** [comment]
Amazing! Thanks 🚀
