### ISSUE TITLE
My docs are not in docs/ but docs/agentscript/0.10.19/

### ISSUE THREAD

**Issue by backspaces** [ankitskvmdam/clean-jsdoc-theme#240]
**Describe the bug**

My opts has: "destination": "docs/", yet when I go there I find two sub dirs: agentscript/0.10.19/
Hopefully this is a documentation issue!
Thanks for the brilliant theme, absolutely fab.

**To Reproduce**

Do a build, with the config below.
Look in docs/
It has a single entry pointing to my repo name
Which has a single entry of my version number
Which finally has the docs!
i.e. rather than docs/ having the documentation, docs/agentscript/0.10.19/ does

**Expected behavior**

I expect the docs to be in docs/
I suppose I could just copy docs/agentscript/0.10.19/  to docs/?

**Screenshots**

Note the url is: https://code.agentscript.org/docs/agentscript/0.10.19/

![Snap 09 03 23-15 21 54](https://github.com/ankitskvmdam/clean-jsdoc-theme/assets/124366/bd5c2991-a1d5-42e1-8e3c-4d5b784ced59)

**Desktop (please complete the following information):**

 - OS: mac
 - Browser chrome
 - Version  115.0.5790.114

**Smartphone (please complete the following information):**

I've not tried using my iphone

**Additional context**

I'm using:   "clean-jsdoc-theme": "4.2.8",

Here's my config/jsdoc.json:
```
{
    "source": {
        "include": ["src", "package.json", "README.md"],
        "includePattern": ".js$",
        "excludePattern": "(node_modules/|docs)"
    },
    "plugins": ["plugins/markdown"],
    "opts": {
        "encoding": "utf8",
        "readme": "./README.md",
        "destination": "docs/",
        "recurse": true,

        "verbose": true,
        "template": "node_modules/clean-jsdoc-theme",
        "displayModuleHeader": true,

        "resizeable": {
            "navbar": {
                "min": "300",
                "max": "600"
            }
        },

        "theme_opts": {
            "sections": ["Classes", "Modules", "Global"],
            "default_theme": "dark",
            "sort": false,
            "footer": "AgentScript version: 0.10.19"
        }
    },
    "markdown": {
        "hardwrap": false,
        "idInHeadings": true
    }
}

```

**Comment by backspaces** [comment]
BTW: I actually need it to be in docs/ due to github pages offering only two places, / and /docs. clean-jsdoc-theme is so cool that I want to try having it be the entry point into the repo!

![Snap 09 03 23-15 28 35](https://github.com/ankitskvmdam/clean-jsdoc-theme/assets/124366/1d13c10a-be8a-46e3-a55a-c20b4a371073)

**Comment by backspaces** [comment]
I am using a temporary redirect by adding docs/index.html:
```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="refresh" content="0;url=https://code.agentscript.org/docs/agentscript/0.10.19/" />
    <title>Redirect</title>
</head>

<body>
    <h3>This is a redirect, waiting...</h3>
</body>

</html>
```

**Comment by ankitskvmdam** [comment]
Hi,

I will try to solve this issue as soon as possible.

Thanks for reporting this issue.

**Comment by ankitskvmdam** [comment]
Hi @backspaces,

Could you please attempt to generate the documentation after removing the package.json entry from your config/jsdoc.json file?

When you include the package.json file as a source, JSDoc gathers information such as the package name and package version. It utilizes this information under the hood to create the output directory (this is the default behavior).

After removing package.json, your configuration file will appear as follows:

```json5
{
    "source": {
        "include": ["src", "README.md"], // <- package.json is removed
        "includePattern": ".js$",
        "excludePattern": "(node_modules/|docs)"
    },
    // ...other properties
}
```

**Comment by backspaces** [comment]
@ankitskvmdam Bingo! Fixed it.
