### ISSUE TITLE
Live coding examples.

### ISSUE THREAD

**Issue by backspaces** [ankitskvmdam/clean-jsdoc-theme#241]
**Is your feature request related to a problem? Please describe.**

We'd like to have tutorials with live code samples. Here's an example:
https://agentscript.org/
Just scroll down to What is Agentscript? It has llovely, simple, uncluttered introductions showing how core Agentscript objects work.

Unfortunately, the dev who created this has left the  team 2 years ago and it's a pretty complex project and very out of date!  One idea was to move that sort of tutorial to clean-jsdoc-theme. It would also be easier to maintain due to being embedded in a well maintained and documented project.

**Describe the solution you'd like**

First of all, we'd like to understand what is already available. We saw the code fragments in the jsdocs. Possibly they could be made "live"? And live code may already be available or being planned.

If there is a solution, we'd like see if it is documented (easy to miss!)
If not, there may be an approach you've considered but not implemented yet.

Possibly the tutorials section would be this would show up?
// SECTION_TYPE
[
    'Classes',
    'Modules',
    'Externals',
    'Events',
    'Namespaces',
    'Mixins',
    'Tutorials',
    'Interfaces',
    'Global'
];

**Describe alternatives you've considered**

You seem to have a codepen interface (I haven't dived into it yet). We considered diving into that to see how well it would solve our problems. The key problem is that codepen would be daunting for beginners learning Agentscript. Sorta "Too Much Information"! Codepen is certainly not uncluttered!

**Additional context**

I think the https://agentscript.org/ sample does a pretty good job showing where we want to go.

And thanks for the great project! Ir's really wonderful!

**Comment by ankitskvmdam** [comment]
I need some time to think on it. I will share something with you soon.

**Comment by backspaces** [comment]
Closing, see #244
