### ISSUE TITLE
[Regression] The `exclude_inherited` option doesn't work anymore

### ISSUE THREAD

**Issue by GMartigny** [ankitskvmdam/clean-jsdoc-theme#242]
**Describe the bug**

The `exclude_inherited` option was introduced in v3.4.0, but was reverted in v4.1.11 with commit 69ad4b6782ec903553a70fca104e40202bf34b50.

Does it was on purpose ? If yes, it should be removed from the [options list](https://github.com/ankitskvmdam/clean-jsdoc-theme#to-exclude-inherited).

**Comment by ankit-bg** [comment]
Now, I realized why we should have a descriptive commit messages.

Unfortunately, I don't remember the reason why I removed it. 

Do we want to have `exclude_inherited` option? If it is needed then we can revert the changes, else I will remove it from the option list.

**Comment by GMartigny** [comment]
> Do we want to have exclude_inherited option?

I personally would love to (as I was [the author](https://github.com/ankitskvmdam/clean-jsdoc-theme/pull/96)), but that's not for me to decide. It's not that big of a difference with the actual code, but one could argue that too many options.

**Comment by ankitskvmdam** [comment]
Sure, I will think give you an update on this by the end of this week. Thanks!

**Comment by ankitskvmdam** [comment]
Reverted changes.

**Comment by ankitskvmdam** [comment]
After doing this change: https://github.com/ankitskvmdam/clean-jsdoc-theme/commit/785b638f4df3a38de98a22c71fbc97c06e69d2f9 in every page only constructor shows.

Could you add this feature again? For now I am reverting everything.

**Comment by GMartigny** [comment]
You were just missing setting the variable in the `publish.js` file. 😉
