### ISSUE TITLE
CodePen example (documentation)

### ISSUE THREAD

**Issue by backspaces** [ankitskvmdam/clean-jsdoc-theme#243]
**Is your feature request related to a problem? Please describe.**

[clean-jsdoc-theme](https://github.com/ankitskvmdam/clean-jsdoc-theme) has a [codepen feature](https://github.com/ankitskvmdam/clean-jsdoc-theme#codepen
) but there is no example of it's use. 

**Describe the solution you'd like**

Could we have demo using it?

**Describe alternatives you've considered**

If there is another way to have live code examples, that might be as good. It also would need a demo! :)

**Additional context**

None that I can think of. .. and Thanks for the great project here!

**Comment by ankit-bg** [comment]
I will try to add examples by the end of this week.

**Comment by ankitskvmdam** [comment]
I will try to add examples by the end of this week.

**Comment by ankitskvmdam** [comment]
Added example for codepen: https://github.com/ankitskvmdam/clean-jsdoc-theme#codepen

For agent script you can do something as follow:

```json5
"theme_opts": {
  "codepen": {
    "enable_for": ["examples"],
    "options": {
      "js_external": "babel",
      "js": "import {AgentArray, AgentList, AgentSet} from 'https://unpkg.com/agentscript@0.10.19/dist/agentscript.js'" // <- You can add all you export in the import state.
    }
  }
}
```

It is not perfect, but at least help the users to start using the library in codepen.

**Comment by ankitskvmdam** [comment]
Also, you need to update `clean-jsdoc-theme` to v4.2.11

**Comment by backspaces** [comment]
Thanks a bunch, I'll try these soon. Briliant!

**Comment by backspaces** [comment]
I'm using
         "clean-jsdoc-theme": "^4.2.13",
Should be OK?

**Comment by ankitskvmdam** [comment]
Yes, it should work!

**Comment by backspaces** [comment]
Closing, see #244

**Comment by backspaces** [comment]
Closing, see #244
