### ISSUE TITLE
Add scripts, codepen, and live code examples (documentation)

### ISSUE THREAD

**Issue by backspaces** [ankitskvmdam/clean-jsdoc-theme#244]
Is your feature request related to a problem? Please describe.

[clean-jsdoc-theme](https://github.com/ankitskvmdam/clean-jsdoc-theme) has a [scripts feature](https://github.com/ankitskvmdam/clean-jsdoc-theme#add-scripts) but there is no example of it's use.

Describe the solution you'd like

Could we have demo using it?

Describe alternatives you've considered

If there iis code in the repo that uses this, you could point us to that.

Additional context

None that I can think of. .. and Thanks for the great project here!

**Comment by ankit-bg** [comment]
I will try to add examples by the end of this week.

**Comment by ankitskvmdam** [comment]
Added examples: 

https://github.com/ankitskvmdam/clean-jsdoc-theme#add-scripts
https://github.com/ankitskvmdam/clean-jsdoc-theme#add-custom-script-files
https://github.com/ankitskvmdam/clean-jsdoc-theme#codepen

**Comment by backspaces** [comment]
Wow, thanks! I'll try them soon.

**Comment by backspaces** [comment]
Any chance we could see this running in one of the [clean-jsdoc-theme](https://github.com/ankitskvmdam/clean-jsdoc-theme/tree/master) demos?

**Comment by backspaces** [comment]
Any chance we could see this running in one of the [clean-jsdoc-theme](https://github.com/ankitskvmdam/clean-jsdoc-theme/tree/master) demos?
BTW should we merge the three issues I've made along these lines

**Comment by ankit-bg** [comment]
Yes we can merge all the three issues.

I will create a demo very soon!

**Comment by ankitskvmdam** [comment]
Yes we can merge all the three issues.

I will create a demo very soon!

**Comment by backspaces** [comment]
Updated to merge the three requests for scripts, code pen and running code.

**Comment by backspaces** [comment]
And thanks for the great work!!

**Comment by backspaces** [comment]
I just found out about MDJS which has three modes for executing code within markdown: https://rocket.modern-web.dev/tools/markdown-javascript/overview/
https://webcomponents.dev/docs/mdjs
https://studio.webcomponents.dev/edit/tS7JYfymt6yeshma8Gn1/README.md?p=README.md

Unfortunately it is not built into jsdoc's markdown (marked). It is available in some markdowns, but not sure if it's worth while. https://remark.js.org/ apparently supports it:
https://betterprogramming.pub/introducing-mdjs-6bedba3d7c6f#:~:text=mdjs%20hooks%20into%20remark%20and,create%20an%20actual%20documentation%20page.

**Comment by ankitskvmdam** [comment]
Here are the examples:
1. Codepen
   1. Code: https://github.com/ankitskvmdam/clean-jsdoc-theme/commit/c768177c8434a6644809a995b240217a7129ccd5
   2. Live: https://ankdev.me/clean-jsdoc-theme/v4/AgentArray.html
   3. When you click on the CodePen icon, the example will open in CodePen in a new tab.
1. Script
   1. I have included a script that will only run for pages that include `agent` in its pathname.
   2. Code: https://github.com/ankitskvmdam/clean-jsdoc-theme/commit/de1ae1f64db3c82c79c1916f2bdf76352d27354f
   3. Live: https://ankdev.me/clean-jsdoc-theme/v4/AgentArray.html
   4. When you open console, you will see "AgentScript" only for this page, if you navigate to some other page, then you will not see it.
1. Live coding
   1. As you mentioned, it is not natively supported by jsdoc's markdown
   2. I have created a workaround for now, you can take hints from this to implement live coding playground: https://github.com/ankitskvmdam/clean-jsdoc-theme/commit/14e3e3f4e8a15aa12d7291175e7dd13f1e83f020#diff-7b52a8fc8cdfedfc010e283ef934bb1670248cbaef3dd4fe8bdab6e0863eec7bR16-R36
   3. Live Preview: https://ankdev.me/clean-jsdoc-theme/v4/AgentArray.html

**Comment by ankitskvmdam** [comment]
If you update to `v4.2.15` then you can do the following:

1. To add script: https://github.com/ankitskvmdam/clean-jsdoc-theme/commit/c83ddb57818025c2fa52fe11eb3d559bff59652b
2. To Add live coding: https://github.com/ankitskvmdam/clean-jsdoc-theme/commit/c83ddb57818025c2fa52fe11eb3d559bff59652b

**Comment by backspaces** [comment]
Somewhat off topic but: I've build a landing page: https://code.agentscript.org/tutorials/Snippets.html
I don't know how to include it within clean-jsdoc-theme.

- I'd love it to take the place of the readme page but it's html, not markdown. Is there a way to  do this?
- I tried making a tutorial/ but the side-bar takes up space and the font colors don't work well together.
   Is there a way to have it be in tutorials but as-is as the landing page for the tutorials which would be normal?
  Or is there an easy way for me to blend in with the dark/light themes but w/o the side-bar.
- I've noticed there are other SECTION_TYPE's: 
      Classes Modules Externals Events Namespaces Mixins Tutorials Interfaces Global
  Would using one of these be where I should place Snippets.html

Thanks for any suggestions! What a great repo!

**Comment by backspaces** [comment]
Oops..I didn't see the demo, that should do the trick! I'll try it next week. Tnx

**Comment by backspaces** [comment]
OK, I've used a variation on your suggestion. You can see it here:  https://code.agentscript.org/docs/
Some questions:
- Can I arrange the tutorials list to not be sorted but in the order of reading? I could just name the tutorials to begin with a number: 0-GettingStarted sort of thing.

- Can I ask some of the nifty code blocks to be full size rather than partial with scrolling?

- Can I set up the Snippets tutorial to always have the two columns adjacent? Resizing the browser width fixes this (nicely done!) but there are still widths that are a bit wonky.

As usual, thanks for the great app!

**Comment by backspaces** [comment]
I'm going to close this for now. I found a way to have the tutorials call out to the Snippets examples which seems more natural. Thanks for the help working all this out!
