### ISSUE TITLE
hideconstructor not tottaly managed

### ISSUE THREAD

**Issue by fletort** [ankitskvmdam/clean-jsdoc-theme#245]
**Describe the bug**

Thus bug was already enter here: https://github.com/ankitskvmdam/clean-jsdoc-theme/issues/98
SO ok now constructor title is not diplay, but is parameters are always here: 

![image](https://github.com/ankitskvmdam/clean-jsdoc-theme/assets/488105/ceb27943-692b-424f-9600-a989909112c2)

**Comment by ankitskvmdam** [comment]
Thanks for reporting this bug. This is fixed: https://github.com/ankitskvmdam/clean-jsdoc-theme/commit/6b8c133a405080806414a2896573fb0de03132dd


Expect this fix in the next release.
