### ISSUE TITLE
When exclude_inherited is turned on, all attributes and methods are missing.

### ISSUE THREAD

**Issue by shawn0326** [ankitskvmdam/clean-jsdoc-theme#250]
**Describe the bug**

When `exclude_inherited` is turned on, all attributes and methods are missing, whether they are inherited from the parent class or not.
Version: 4.2.13

**Comment by ankitskvmdam** [comment]
@GMartigny Could you please help us?

**Comment by GMartigny** [comment]
I can reproduce, so I'm looking into it.
