### ISSUE TITLE
Only generate new header ids when the content changes

### ISSUE THREAD

**Issue by cewert** [ankitskvmdam/clean-jsdoc-theme#254]
**Is your feature request related to a problem? Please describe.**

I'm using jsdoc and this github action https://github.com/stefanzweifel/git-auto-commit-action to automatically update the doc files after a PR is merged.

My problem is that because this theme generates new header ids for each file regardless if there has been changes, that means that in order for me to make this workflow work, we would need to update every single doc .html file because of the new ids instead of just the files with changes.

**Describe the solution you'd like**

Only modify the .html files if there have been changes

**Describe alternatives you've considered**

Add some kind of config setting to allow users to opt out/in to this behavior

**Additional context**

These are the ids I'm talking about:

![clean-jsdoc-id](https://github.com/ankitskvmdam/clean-jsdoc-theme/assets/16514652/e48bbe12-46f7-43c3-bcff-cbd0352c57fe)

**Comment by ankitskvmdam** [comment]
Thanks for creating this issue. I will look into this.

**Comment by ankitskvmdam** [comment]
This issue have been fixed in `v4.2.17`
