### ISSUE TITLE
The docs change every  build even though no changes have been made.

### ISSUE THREAD

**Issue by backspaces** [ankitskvmdam/clean-jsdoc-theme#269]
**Describe the bug**

Every time the docs get regenerated, they show changes having been made, even when I've made no changes in the docs.

This causes git bloat.

**To Reproduce**
Every commit, I run this:
`rm -rf docs/* && jsdoc -c config/cleantheme/jsdoc.json`

Git reports the docs have changed even though I have made no changes.

**Expected behavior**

If I make no changes in the docs, the docs/ dir should show no changes after a rebuild 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] Mac Ventura 13.3.1
 - Browser [e.g. chrome, safari, firefox] chrome
 - Version [e.g. 22]         "clean-jsdoc-theme": "^4.2.17",

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ankitskvmdam** [comment]
Thanks for reporting, I will look into this.

**Comment by backspaces** [comment]
Sure, and Thanks!

**Comment by ankitskvmdam** [comment]
I am not able to reproduce. I am attaching a video of what I did.




https://github.com/ankitskvmdam/clean-jsdoc-theme/assets/22586210/ad829289-3c40-49e1-85d2-f5fbd04c32e6


Could you help in reproducing it?

**Comment by backspaces** [comment]
OK, thanks for the help, very useful. It must be on my end, Lets close this for now,
