### ISSUE TITLE
Disable scrollbar manipulation?

### ISSUE THREAD

**Issue by jsumners-nr** [ankitskvmdam/clean-jsdoc-theme#281]
https://github.com/ankitskvmdam/clean-jsdoc-theme/blob/edeee60f3c0c18e27f18fa39d241c98566324330/static/styles/clean-jsdoc-theme-base.css#L883-L892

Is it possible to disable manipulation of the scrollbar? The styling of it makes the scrollbar basically invisible, and thus makes it extremely difficult to determine location in long documents.

**Comment by ankitskvmdam** [comment]
@jsumners-nr Thanks for creating this issue! I will add an option to disable the manipulation of the scrollbar.

**Comment by jsumners-nr** [comment]
Thank you.
