### ISSUE TITLE
Keep the current tab in the side menu highlighted.

### ISSUE THREAD

**Issue by backspaces** [ankitskvmdam/clean-jsdoc-theme#283]
**Is your feature request related to a problem? Please describe.**

I sometimes am unsure of which page I'm looking at. Highlighting it in the list on the left would solve this.

**Describe the solution you'd like**

Keep the current tab I’m reading in the side menu highlighted.

**Describe alternatives you've considered**

Possibly a css rule I could add?

**Additional context**

Here's a comment from one of my team members:

@backspaces: little UI note — keep the current tab I’m reading in the side menu highlighted. In this example, I’m reading page 4 - Model but forgot which tab I was on. I had to scroll back to the top of the page to see where to  go next :]

![image](https://github.com/ankitskvmdam/clean-jsdoc-theme/assets/124366/bfee9d35-1b54-47ed-b7ae-2687c69cccfe)

**Comment by ankitskvmdam** [comment]
@backspaces Sure, I will add a css rule to highlight current page's url/href.

**Comment by ankitskvmdam** [comment]
Fixed: https://github.com/ankitskvmdam/clean-jsdoc-theme/commit/8f450cb40ca8c5b3cd94ebb8d4131d9425032714

**Comment by ankitskvmdam** [comment]
Update `clean-jsdoc-theme` to `v4.2.18`

**Comment by backspaces** [comment]
Hi. How do I turn on the highlighting? I'm running 4.2.18 as you suggest. Thanks!

**Comment by ankitskvmdam** [comment]
@backspaces It should be enabled by default.

**Comment by ankitskvmdam** [comment]
I think there is a bug. I will look into this. Thanks for the feedback!
