### ISSUE TITLE
@fires breaks layout

### ISSUE THREAD

**Issue by riksnelders** [ankitskvmdam/clean-jsdoc-theme#38]
When using @fires layout breaks. Doesn't happen when I do not use @fires in my comments.
See attached screenshot. 

Because of w-100 class most probably the layout breaks.  

![image](https://user-images.githubusercontent.com/15074808/74543656-0f3a3780-4f46-11ea-8fb3-15331693846b.png)

**Comment by ankitskvmdam** [comment]
Thanks for reporting this

**Comment by ankitskvmdam** [comment]
Close by [#39](https://github.com/ankitskvmdam/clean-jsdoc-theme/pull/39)
