### ISSUE TITLE
Add extra left padding for markdown rendered lists

### ISSUE THREAD

**Issue by deep5050** [ankitskvmdam/clean-jsdoc-theme#40]
Need some extra left padding when rendering lists from README.md

Example :

![Screenshot_2020-06-05-13-55-22-309_com android chrome](https://user-images.githubusercontent.com/27947066/83854469-61d97280-a734-11ea-947b-be8bbacc5de3.jpg)

**Comment by ankitskvmdam** [comment]
Thanks for reporting. We'll try to solve this as soon as possible.
