### ISSUE TITLE
Malformed HTML when parsing 'default' JSDoc tags

### ISSUE THREAD

**Issue by rdipardo** [ankitskvmdam/clean-jsdoc-theme#48]
**Describe the bug**

When a member has a `@default` or `@defaultvalue` tag, the closing `div` of the HTML description is malformed (specifically, it looks like this: `</div`)

**To Reproduce**

1. Clone [my fork][]
2. Run `npm i && npm run doc:issue`
2. Open the generated `@default-tag-issue/doc/CSS.html` file in vim (or some other editor)
3. Using vim, enter `:g/.<\/div$`, or type `.<\/div$` into your editor's search box with regular expressions activated
4. There will be 4 matches, around lines `146`, `220`, `294`, `368` (see screenshots below)

**Expected behavior**

`@default` metadata should render as valid HTML.

For now, the problem can be fixed by removing all `@default` and `@defaultvalue` tags from the JSDoc markup; users should be advised not to use these tags until the bug is patched.

**Screenshots**

Using the `@default` tag . . .

![Screenshot_2020-11-12_01-35-42](https://user-images.githubusercontent.com/59004801/98988242-59f8d800-24f5-11eb-803b-f161e908f573.png)

. . . produces HTML like this:

![malformed_div_1](https://user-images.githubusercontent.com/59004801/98987877-d50dbe80-24f4-11eb-91e5-c92c8a886c5a.png)

. . . in every place where the `@default` tag  is encountered:

![malformed_div_2](https://user-images.githubusercontent.com/59004801/98988309-7432b600-24f5-11eb-8dc1-ca80415557fb.png)

![malformed_div_3](https://user-images.githubusercontent.com/59004801/98988323-7ac12d80-24f5-11eb-8d5a-fc69f537ec9a.png)

. . . which breaks the layout:

![Screenshot_2020-11-12_01-36-44](https://user-images.githubusercontent.com/59004801/98988390-96c4cf00-24f5-11eb-92f0-111218b37021.png)

**Desktop**
 - OS: Debian Buster 10.5
 - Browser Firefox
 - Version 82.0.3
- `clean-jsdoc-theme` version 2.2.13

**Additional context**

- it behaves the same with the `@defaultvalue` [alternative tag][] as with `@default`
- same results using the `light` or `dark` theme

[my fork]: https://github.com/rdipardo/clean-jsdoc-theme
[alternative tag]: https://jsdoc.app/tags-default.html

**Comment by ankitskvmdam** [comment]
Thanks for reporting. I have fix the bug and also publish it on npm (clean-jsdoc-theme^2.2.14).
