### ISSUE TITLE
"add_style_path" feature failing

### ISSUE THREAD

**Issue by EmrajiPower** [ankitskvmdam/clean-jsdoc-theme#52]
Hello im trying to configure some css in my docs, and im trying to setup some colors and custom fonts. It is my code: 

`
body {
  font-family: "Airbnb Cereal App", "Airbnb Cereal App Book";
}
nav {
  background: linear-gradient(
    180deg,
    rgb(3, 136, 163) 30%,
    rgb(0, 195, 116) 90%
  );
}
h1.page-title::after 
  background-color: rgb(0, 195, 116);
}
...
`

and there is the clean-jsdoc-theme config:

`"opts": {
    ...
    "theme_opts": {
     ...
      "add_style_path": ["./index.css"]
    }`

when i run the code seems that its not working fine, what is wrong? can you fix that issue please?

**Comment by ankitskvmdam** [comment]
Hi, @EmrajiPower, is it throwing any error?

**Comment by EmrajiPower** [comment]
@ankitskvmdam console is throwing that error:
![image](https://user-images.githubusercontent.com/32020190/101684237-18941380-3a34-11eb-94af-7f1b61083ea4.png)

**Comment by EmrajiPower** [comment]
i found the problem, while im trying to use `./docs/` in my route by default import it is using  `docs/` already. thanks for the feedback.
