### ISSUE TITLE
Closing/Opening Classes/Modules to minimize size of left hand panel.

### ISSUE THREAD

**Issue by backspaces** [ankitskvmdam/clean-jsdoc-theme#57]
**Is your feature request related to a problem? Please describe.**

Because I'm documenting many classes/modules with several functions/methods, I'd like to be able to "close" classes/files in the left side index of functions.

Example: https://agentscript.org/docs/
The top class is AgentArray. I'd like to close it by clicking on the name, an accordion style action.

Ditto for the rest of the top level classes/modules.

**Describe the solution you'd like**

Clicking on a top level item closes it, showing only the top level name. I think "accordion" is the css term.

**Describe alternatives you've considered**

Possibly separate pages per top level group. So the left hand side has links to the separate page.

Not sure how to do this with jsDoc.

**Additional context**

I think the url above should do the trick.

And I gotta THANK YOU for this terrific tool. Wow!

**Comment by backspaces** [comment]
Here's an example with this behavior:
https://clenemt.github.io/docdash/module-ink_collector-ACollector.html

**Comment by ankitskvmdam** [comment]
Sorry for the late reply!
I think we can add accordions for this. Something like GitHub docs: https://docs.github.com/en/github and by default all the accordions are collapsed.
What your take on this?

**Comment by ankitskvmdam** [comment]
![Screenshot 2021-01-31 at 4 58 54 PM](https://user-images.githubusercontent.com/22586210/106382452-b9c09a00-63e5-11eb-95c3-e738bcc67b0f.png)

**Comment by backspaces** [comment]
Yes, that's exactly what I had in mind!

**Comment by ankitskvmdam** [comment]
I'll try to work on it this week! Expect this feature to land in the next release by the end coming week.

**Comment by backspaces** [comment]
Wow, thanks!

**Comment by ankitskvmdam** [comment]
Added this feature and released v3.0.7
