### ISSUE TITLE
Add support for @see documentation links

### ISSUE THREAD

**Issue by curthusting** [ankitskvmdam/clean-jsdoc-theme#58]
**Is your feature request related to a problem? Please describe.**

I am attempting to link to external resources via the jsdoc examples, i.e.;
```
/**
 * The jQuery plugin namespace.
 * @external "jQuery.fn"
 * @see {@link http://learn.jquery.com/plugins/|jQuery Plugins}
 */
```

**Describe the solution you'd like**

The built in template that comes with jsdoc provides a link to the external resource
![image](https://user-images.githubusercontent.com/5934577/108441172-9473be80-7222-11eb-9b69-53764aee2301.png)
whereas it appears this is ignored within this template
![image](https://user-images.githubusercontent.com/5934577/108441295-d00e8880-7222-11eb-9815-f19b1aa33aa3.png)

**Describe alternatives you've considered**

I have tried implementing this through alternate jsdoc tags, but to no avail...and if I had a greater knowledge of how to customize the templates, I would submit a PR, but being so new to jsdoc I am not aware of any other solution

**Additional context**

If you could point me in the right direction, I could try my hand at submitting a PR for this, but I would need some assistance getting started

**Comment by ankitskvmdam** [comment]
Thanks for reporting an issue. I will look into this and guide you accordingly.
