### ISSUE TITLE
Hello, It's me again!

### ISSUE THREAD

**Issue by TakenKills** [ankitskvmdam/clean-jsdoc-theme#61]
**Describe the bug**

I don't know if this is described as a bug but in my previous issue I asked if there is a way to remove the source tags and there was a new update on the package that sort of added that feature there are still some source tags in the documentation of my code.

**To Reproduce**

1. Write a class or something.

2. Add a property to the class and add This jsdoc comment on top of it 
        `/**
         * Some description.
         * @default null
         * @type { String } 
         */`

**Expected behavior**

It should not add a `source` tag.

**Screenshots**

![image](https://user-images.githubusercontent.com/65789369/112544329-884dc480-8dbf-11eb-8fc2-8618d6e88ff6.png)

**Desktop:**
 - OS: Windows
 - Browser: Brave
 - Version: 3.0.10

**Comment by ankitskvmdam** [comment]
Did you update the jsdoc config file?

**Comment by ankitskvmdam** [comment]
I just realized in previous comment (https://github.com/ankitskvmdam/clean-jsdoc-theme/issues/60#issuecomment-807074900) I made a typo.. Instead of `defaults` you have to use `default`

Hope this works.

**Comment by TakenKills** [comment]
Ahh defaults instead of default

**Comment by TakenKills** [comment]
hm, I already had it as `defaults`

**Comment by ankitskvmdam** [comment]
use `default`

**Comment by TakenKills** [comment]
Oh, I read it wrong My bad there aren't any source tags now. Thanks!
