### ISSUE TITLE
Collapse main sections

### ISSUE THREAD

**Issue by ivmartel** [ankitskvmdam/clean-jsdoc-theme#62]
It would be nice to be able to fold main sections ('Classes', 'Modules', 'Externals'...) for projects that have a large number of classes, modules...

**Comment by ankitskvmdam** [comment]
Thanks for this feature request. It would be nice if you can share some design related to this. After that we can try to implement as soon as possible.

**Comment by ankitskvmdam** [comment]
![Screenshot 2021-03-28 at 9 23 35 PM](https://user-images.githubusercontent.com/22586210/112758411-e8d14180-900b-11eb-8126-ead0f07c5725.png)

This is what I did. This implementation will release with version 3.1.0

**Comment by ankitskvmdam** [comment]
This is fixed in v3.1.0
