### ISSUE TITLE
Returned type font size

### ISSUE THREAD

**Issue by ivmartel** [ankitskvmdam/clean-jsdoc-theme#70]
**Describe the bug**

Note sure if is a bug, but the font of the returned type seems big, see for example [here](https://ankdev.me/clean-jsdoc-theme/dark/Energy.html#unit) in your demo.

**Comment by ankit-kumar-kr** [comment]
It is same as the member name., try to inspect the element.

**Comment by ivmartel** [comment]
The problem seems to be in the [reset.css#L116](https://github.com/ankitskvmdam/clean-jsdoc-theme/blob/master/static/styles/reset.css#L116), the link font size is reset. 
So if the returned type is an inner class, a link is created for it as for the `unit` method that returns an `EnergyUnit` in the demo link I sent above.

**Comment by ankitskvmdam** [comment]
Oh.. I will fix this as soon as possible..
