### ISSUE TITLE
Unable to load template: Unexpected token {

### ISSUE THREAD

**Issue by rodigu** [ankitskvmdam/clean-jsdoc-theme#75]
**Describe the bug**

Fatal error when trying to generate the document.

**To Reproduce**

Theme installed locally through `npm install --save-dev`
`jsdoc -t 'node_modules/clean-jsdoc-theme' 'code.js'`

**Expected behavior**

JSDoc regular output

**Screenshots**

![image](https://user-images.githubusercontent.com/58960796/121446033-0f471d80-c969-11eb-8445-fcda95cfc7c7.png)
![image](https://user-images.githubusercontent.com/58960796/121446180-5af9c700-c969-11eb-9b01-0a1f6ee283cd.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser N/A

**Smartphone (please complete the following information):**
 - Version 3.2.7

**Additional context**

Problem happens if using `npm run` or the conf.js "theme" option for JSDoc

**Comment by ankitskvmdam** [comment]
Hi @rodigu, I assume you are running your command on the `cmd terminal`.  You can try, `jsdoc -t .\node_modules\clean-jsdoc-theme .\code.js`. 

Hope this will fix the issue.

**Comment by rodigu** [comment]
Hi @ankitskvmdam, thanks for the response!
Unfortunately, that also didn't work. I am using the Windows PowerShell, sorry for not making it clear. I have been using `/` instead of `\` because I already knew it worked with other commands.
I am starting to think this might actually be a problem with JSDoc, since I ran into the same problem even when trying previous versions of clean-jsdoc-theme, as well as checking out other JSDoc themes. It does not happen with all themes though, since jaguarjs-jsdoc and jsdoc-skyceil still work fine for me.

**Comment by ankitskvmdam** [comment]
Can you share the complete error message.
________________________________

**Comment by ankitskvmdam** [comment]
It would be nice if you can share the complete error message, as it is hard toh guess the actual problem. Also, is it possible to share the `code.js` file, for which you want to generate docs.

**Comment by ankitskvmdam** [comment]
Thanks for sharing.. I will look into it and update you.

**Comment by ankitskvmdam** [comment]
Hi @rodigu, I tried the same on my machine and it is working fine. Which version of `clean-jsdoc-theme` and `jsdoc` you are using. I have tested with:
```
clean-jsdoc-theme: v3.2.7
jsdoc: v3.6.7
OS: Window 10
```
You can try to uninstall and install the package...
If the issue persists can you create a minimal repository to reproduce the error.

**Comment by rodigu** [comment]
I still have the same issues after installing and uninstalling `clean-jsdoc-theme` and doing the same for `jsdoc`. I will try doing what you suggested with the minimal repository later today and get back to you. My npm version is 5.6.0 by the way, although I am not sure if this helps

**Comment by ankitskvmdam** [comment]
Hi @rodigu, I have tried running the same command using `npm version 5.6.0` (`node version 9.11.2`) and I am getting the same error. When I tried with `npm version 6.1.0` (`node version 10.3.0`) it works. So, I think you need at least npm version 6.1.0

**Comment by rodigu** [comment]
It worked! Thank you so much😀
