### ISSUE TITLE
Use fixed-width font for code samples

### ISSUE THREAD

**Issue by markwpearce** [ankitskvmdam/clean-jsdoc-theme#82]
**Is your feature request related to a problem? Please describe.**

Variable-width fonts are non-standard when viewing code... but currently clean-jsdoc-theme use a variable width font for markdown samples

**Describe the solution you'd like**

I think by default, the code samples in markdown should be fixed-width (monospace), but potentially with an option for variable-width

**Comment by ankitskvmdam** [comment]
@markwpearce Thanks for this issue. Can you please show me where? Or else you can create a PR that solve this issue?
