### ISSUE TITLE
a lonely console.log statement

### ISSUE THREAD

**Issue by volker-schukai** [ankitskvmdam/clean-jsdoc-theme#83]
here is a forgotten console.log statement

https://github.com/ankitskvmdam/clean-jsdoc-theme/blob/e53923c2bfccf09c385e2ef57bb8b32a4382931a/tmpl/layout.tmpl#L157

I think this should be removed.

**Comment by ankitskvmdam** [comment]
Hi @volker-schukai, yes we should remove this. Would you like to create a PR for this?

**Comment by volker-schukai** [comment]
https://github.com/ankitskvmdam/clean-jsdoc-theme/pull/84
