### ISSUE TITLE
Sub namespaces in parent list

### ISSUE THREAD

**Issue by sgarnotel** [ankitskvmdam/clean-jsdoc-theme#87]
**Is your feature request related to a problem? Please describe.**

For large projects, sub-namespaces (i.e. @namespace API.womething) are not in the `<ul>` of the parent namespace.
It is very difficult to read, especially if you have an architecture like:
```
api
  module1
  module2
lib
  module1
  module2
...
```

**Describe the solution you'd like**

Include the sub-namespace (or sub-modules, ...) directly in the parent list.

**Describe alternatives you've considered**

RAS

**Additional context**

Have a look on https://github.com/sgarnotel/clean-jsdoc-theme/tree/subitem-as-submenu, the implementation is clearly dirty but it works.

**Comment by ankitskvmdam** [comment]
@sgarnotel , Sorry for the late reply. I agree with you. Can you create a PR?
