### ISSUE TITLE
Tutorials that share their name with a class will have that classes methods dropdown

### ISSUE THREAD

**Issue by apteryxxyz** [ankitskvmdam/clean-jsdoc-theme#89]
**Describe the bug**

A tutorial that shares its name with a class will have that classes dropdown menu containing the methods.

**To Reproduce**

1. Create a class and add at least one method (e.g. `User`)
2. Create a tutorial that has the same name as the class (e.g. `User.md`)
3. Generate docs and open
4. The tutorial (e.g. `User`) will have a dropdown

**Expected behavior**

For the tutorial to not have a dropdown, the methods are already explained on the page of the class.

**Screenshots**

![Capture](https://user-images.githubusercontent.com/40654585/139592518-944db722-636e-497a-a7b8-97f4d548c261.PNG)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 95

**Comment by ankitskvmdam** [comment]
Hi @apteryxxyz , thanks for reporting this bug.  This bug will be fixed in the next release.
