### ISSUE TITLE
Disabled source still produces 'details' block

### ISSUE THREAD

**Issue by movitto** [ankitskvmdam/clean-jsdoc-theme#90]
Greetings, thanks for this library, we are looking to use it to generate some documentation for a new project.

Related to #60 when source is disabled via the outputSourceFiles: false flag, the source is removed but the surrounding block remains. Please see the attached screenshot. It would be nice if this was removed as well.

![Screenshot](https://user-images.githubusercontent.com/166845/143311326-138c9b6e-a1d4-48ac-be3d-50313ba4c132.png)

Thanks again!

**Comment by ankitskvmdam** [comment]
Hi @movitto , sorry for the late reply. I look into it.

**Comment by movitto** [comment]
:+1:
