### ISSUE TITLE
@hideconstructor

### ISSUE THREAD

**Issue by ghazette** [ankitskvmdam/clean-jsdoc-theme#98]
@hideconstructor on top of a class does not hide the constructor

```javascript
/**
 * Constructor should be hidden
 * @hideconstructor
 */
class Test {
	constructor(hidemepls) {
		console.log('i am a constructor');
	}
}
```

![image](https://user-images.githubusercontent.com/28451628/156002042-1103d383-4432-464b-9606-1f3f94d5fc22.png)

**Comment by ankitskvmdam** [comment]
Hi, @ghazette sorry for the late reply. Thanks for reporting this issue. I will look into it and update you.

**Comment by ankitskvmdam** [comment]
Hi, @ghazette , this issue is fixed.
